name: Publish a release
on:
  release:
    types: [ published ]
jobs:
  publish-docker:
    name: Docker build image and publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read package.json
        uses: zvonimirsun/read-package-version-actions@v2
        id: getVersion

      - name: Push Version ${{ steps.getVersion.outputs.version }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bawix/testik-front:${{ steps.getVersion.outputs.version }}

      - name: Push Latest
        if: ${{ !contains(steps.getVersion.outputs.version, '-') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bawix/testik-front:latest
